/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiLinesRouteImport } from './routes/api/lines'
import { Route as ApiLiveSyncRouteImport } from './routes/api/live-sync'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiWriteLineRouteImport } from './routes/api/write-line'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as MediaPostIdRouteImport } from './routes/media/$postId'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as ApiImagesKeyRouteImport } from './routes/api/images/$key'
import { Route as ApiSyncManualRouteImport } from './routes/api/sync/manual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinesRoute = ApiLinesRouteImport.update({
  id: '/api/lines',
  path: '/api/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSyncRoute = ApiLiveSyncRouteImport.update({
  id: '/api/live-sync',
  path: '/api/live-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWriteLineRoute = ApiWriteLineRouteImport.update({
  id: '/api/write-line',
  path: '/api/write-line',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPostIdRoute = MediaPostIdRouteImport.update({
  id: '/media/$postId',
  path: '/media/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesKeyRoute = ApiImagesKeyRouteImport.update({
  id: '/api/images/$key',
  path: '/api/images/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncManualRoute = ApiSyncManualRouteImport.update({
  id: '/api/sync/manual',
  path: '/api/sync/manual',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/tips': typeof TipsRoute
  '/api/content': typeof ApiContentRoute
  '/api/lines': typeof ApiLinesRoute
  '/api/live-sync': typeof ApiLiveSyncRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/write-line': typeof ApiWriteLineRoute
  '/media/$postId': typeof MediaPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/media/': typeof MediaIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/api/sync/manual': typeof ApiSyncManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/tips': typeof TipsRoute
  '/api/content': typeof ApiContentRoute
  '/api/lines': typeof ApiLinesRoute
  '/api/live-sync': typeof ApiLiveSyncRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/write-line': typeof ApiWriteLineRoute
  '/media/$postId': typeof MediaPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/media': typeof MediaIndexRoute
  '/posts': typeof PostsIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/api/sync/manual': typeof ApiSyncManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/tips': typeof TipsRoute
  '/api/content': typeof ApiContentRoute
  '/api/lines': typeof ApiLinesRoute
  '/api/live-sync': typeof ApiLiveSyncRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/write-line': typeof ApiWriteLineRoute
  '/media/$postId': typeof MediaPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/media/': typeof MediaIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/api/sync/manual': typeof ApiSyncManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/tips'
    | '/api/content'
    | '/api/lines'
    | '/api/live-sync'
    | '/api/stats'
    | '/api/upload'
    | '/api/write-line'
    | '/media/$postId'
    | '/posts/$postId'
    | '/media/'
    | '/posts/'
    | '/api/images/$key'
    | '/api/sync/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/tips'
    | '/api/content'
    | '/api/lines'
    | '/api/live-sync'
    | '/api/stats'
    | '/api/upload'
    | '/api/write-line'
    | '/media/$postId'
    | '/posts/$postId'
    | '/media'
    | '/posts'
    | '/api/images/$key'
    | '/api/sync/manual'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/tips'
    | '/api/content'
    | '/api/lines'
    | '/api/live-sync'
    | '/api/stats'
    | '/api/upload'
    | '/api/write-line'
    | '/media/$postId'
    | '/posts/$postId'
    | '/media/'
    | '/posts/'
    | '/api/images/$key'
    | '/api/sync/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  TipsRoute: typeof TipsRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiLinesRoute: typeof ApiLinesRoute
  ApiLiveSyncRoute: typeof ApiLiveSyncRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWriteLineRoute: typeof ApiWriteLineRoute
  MediaPostIdRoute: typeof MediaPostIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  MediaIndexRoute: typeof MediaIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiImagesKeyRoute: typeof ApiImagesKeyRoute
  ApiSyncManualRoute: typeof ApiSyncManualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lines': {
      id: '/api/lines'
      path: '/api/lines'
      fullPath: '/api/lines'
      preLoaderRoute: typeof ApiLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-sync': {
      id: '/api/live-sync'
      path: '/api/live-sync'
      fullPath: '/api/live-sync'
      preLoaderRoute: typeof ApiLiveSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/write-line': {
      id: '/api/write-line'
      path: '/api/write-line'
      fullPath: '/api/write-line'
      preLoaderRoute: typeof ApiWriteLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$postId': {
      id: '/media/$postId'
      path: '/media/$postId'
      fullPath: '/media/$postId'
      preLoaderRoute: typeof MediaPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$key': {
      id: '/api/images/$key'
      path: '/api/images/$key'
      fullPath: '/api/images/$key'
      preLoaderRoute: typeof ApiImagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/manual': {
      id: '/api/sync/manual'
      path: '/api/sync/manual'
      fullPath: '/api/sync/manual'
      preLoaderRoute: typeof ApiSyncManualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  TipsRoute: TipsRoute,
  ApiContentRoute: ApiContentRoute,
  ApiLinesRoute: ApiLinesRoute,
  ApiLiveSyncRoute: ApiLiveSyncRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWriteLineRoute: ApiWriteLineRoute,
  MediaPostIdRoute: MediaPostIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  MediaIndexRoute: MediaIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiImagesKeyRoute: ApiImagesKeyRoute,
  ApiSyncManualRoute: ApiSyncManualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
